---
version: '3'

services:
  drupal:
    image: wdseelig:d789
    container_name: WCGOPD789
    environment:
      DRUPAL_DATABASE_HOST: 'mysql'
      DRUPAL_DATABASE_PORT: '3306'
      DRUPAL_DATABASE_NAME: 'washgopc_GOPV7V2'
      DRUPAL_DATABASE_USERNAME: 'washgopc_gopdb'
      DRUPAL_DATABASE_PASSWORD: '18WMTNwcta65'
      # TODO: Create a new hash salt for this.
      DRUPAL_HASH_SALT: 'fe918c992fb1bcfa01f32303c8b21f3d0a0'
      DRUPAL_DOWNLOAD_IF_NOT_PRESENT: 'false'
    ports:
      - "80:80"
      - "2222:22"
    restart: on-failure
    # Share the project into the container for local development. Comment out
    # this line to test the production-ready pre-built container codebase.
    volumes: ['./:/var/www/html:rw,delegated']

  mysql:
    image: mysql:5.7
    container_name: drupal789-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: washgopc_GOPV7V2
      MYSQL_USER: washgopc_gopdb
      MYSQL_PASSWORD: 18WMTNwcta65
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
        
