<?php
/**
 * Implements hook_commerce_checkout_pane_info()
 */
function commerce_gopcheckout_commerce_checkout_pane_info() {
  $panes['commerce_gopcheckout'] = array(
    'title' => t('GOP Checkout On January 20'),
    'page' => 'checkout',
    'weight' => 10,
    'base' => 'commerce_gopcheckout_pane',
  );
  return $panes;
}
function commerce_gopcheckout_form_commerce_checkout_form_alter(&$form,
	&$form_state,$form_id)
{
	variable_set("aaa5","Made it into the form alter routine on February 18");
	global $user;
	switch($form_id){
		case 'commerce_checkout_form_checkout':
			if (isset ($form[customer_profile_accountinformationi])){
				$form['body'] = array(
				'#markup' => '<p><h3>Please fill in the form below and then proceed to 
					the payment process by clicking on the Continue to Next Step button 
					at the bottom of the form</h3></p>',
				'#weight' => '0'
				);
				break;
		 	}
			elseif (isset($form[customer_profile_member])){
				$order = commerce_cart_order_load($user->uid);
				$order_wrapper = entity_metadata_wrapper('commerce_order', $order);
				if (!$order_wrapper->field_payatdoor->value()){
				$form['body'] = array(
					'#markup' => '<p><h3>We are looking forward to seeing you! Please fill
					in your email<br>address below so that we will be able to get
					in touch with you<br>about this event. Then click on the Finish
					Registering button below.<br><br>
					See you there!</h3></p>',
					'#weight' => '0'
					);
				}
				else{
					$form['body'] = array(
					'#markup' => '<p><h3>We are looking forward to seeing you! Please fill
					in your email<br>address below so that we will be able to get
					in touch with you<br>about this event. Then click on the Finish
					Registering Button below.<br><br>REMINDER: We can only accept cash,
					checks, and money orders at the door [No credit cards].<br><br>
					See you there!</h3></p>',
					'#weight' => '0'
					);
				}
				
//				$form['#action'] = '/ForumConfirmation';
				$form['buttons']['continue']['#value'] = 'Finish Registering';
				array_unshift($form['buttons']['continue']['#submit'],
					'commerce_gopcheckout_finishmemberorder');
				$form['customer_profile_member']['field_wcgopmembername']
					['#access'] = FALSE;
//				$form['buttons']['continue']['#access'] = FALSE;
//				$form['buttons']['cancel']['#access'] = FALSE;
				$form['customer_profile_member']['field_wcgopordername']['und']['0']
					['value']['#title'] = 'The name that is on this order';
				$form['customer_profile_member']['field_wcgopordername']['und']['0']
					['#description'] = 'The member name on this order';
//				$form['actions']['continue']['#type'] = 'submit';
//				$form['actions']['continue']['#submit'] = 
//					'commerce_gopcheckout_finishmemberorder';
//				array_unshift($form['actions']['continue']['#submit'],
//					'commerce_gopcheckout_finishmemberorder');		
				$form['account']['login']['mail']['#required'] = FALSE;
				$form['account']['#access'] = FALSE;
				$order = commerce_cart_order_load($user->uid);
				$order_wrapper = entity_metadata_wrapper('commerce_order', $order);
				$form['customer_profile_member']['field_wcgopordername']['und']['0']
					['value']['#value'] = $order_wrapper->field_wcgopmembername->raw();
				break;
			}
			elseif (isset($form[customer_profile_guest])){
				$form['body'] = array(
					'#markup' => '<p><h3>Please enter a little information about this 
						individual.  Only the first and last names are mandatory.</h3></p>',
					'#weight' => '-10'
					);
					$form['buttons']['continue']['#value'] = 'Complete this Registration';
					$form['buttons']['continue']['#submit'] = array(
					     'commerce_gopcheckout_completenonpayingcustomer');
				break;
			}
			else {
/*
		This is the normal case when our customer profile is billing.  This code
		will run if an order is in the "shopping cart" state [i.e., is not
		completed].  The url will be home/checkout/order#
*/
		
				$order = commerce_cart_order_load($user->uid);
				$order_wrapper = entity_metadata_wrapper('commerce_order', $order);
				if ($order_wrapper->field_payatdoor->value()){
					$form['body'] = array(
							'#markup' => '<p><h3>Even though you are paying at the door, 
							     Federal and state law require us to collect this information.
							     Please fill in the form below and then complete this process
							     by clicking on the Continue to Next Step button at the bottom
							      of the form.  Please note that we can only accept checks and
							       money orders at the door.</h3></p>',
							'#weight' => '-10'
				);
				}
				else {
					$form['body'] = array(
							'#markup' => '<p><h3>Federal and state law require us to 
								collect this information.  Please fill in the form below and 
								then proceed to the payment process by clicking on the Continue 
								to the very very Next Step button at the bottom of the 
								form</h3></p>',
							'#weight' => '-10'
				);		
				}
				$statesarray = array (
		  		'visible' => array (
		    		 ':input[name="customer_profile_billing[field_gopstoreemployed]
		    		 [und]"]' => array('value' => '1')
		     	)
		     ); 
				$form['customer_profile_billing']['field_gopstoreemployer']
					['#states'] = $statesarray;
				$form['customer_profile_billing']['field_gopstoremyemployeraddress']
					['#states'] = $statesarray;
				$form['buttons']['continue']['#value'] = 'Continue to the Next Step';
/*
		Here we take over the routing of the checkout process by changing the 
		#submit property of the continue button. It is necessary to make our routine
		[commerce_gopcheckout_gopordercheck] first in line [hence the 
		array_unshift].  Note that this leaves the rest of the commerce form 
		processing submit routines intact.  They will take over the job of 
		processing this form after my routine, gopordercheck, is complete, unless 
		either the paidbycheck indicator is checked on the form or the payatthedoor
		indicator has been set for this order.  In these cases we'll just go 
		directly to checkout complete.  
*/
				array_unshift($form['buttons']['continue']['#submit'],
					'commerce_gopcheckout_gopordercheck');
		
			break;
	}
		case 'commerce_checkout_form_review' :
			$form['buttons']['continue']['#value'] = "Make Your Stripe Payment";
			break;
	return;
}
}
/*
		This is the routine that processes a click of the "Continue to the next
		step" button on the Commerce Checkout form.  
*/
function commerce_gopcheckout_gopordercheck($form,&$form_state) {
		global $user;
		$order = commerce_cart_order_load($user->uid);
		$order_wrapper = entity_metadata_wrapper('commerce_order', $order);
		$order_wrapper->field_orderattached->set($order->order_id);
		$order_total = $order_wrapper->commerce_order_total->value();
		$amount = commerce_currency_amount_to_decimal($order_total['amount'],'USD');
		if ($form['customer_profile_billing']['field_paidbycheck']['und']
		['#value'] || $order_wrapper->field_payatdoor->raw() || ($amount == 0)) { 
			commerce_order_status_update($order,'pending');
			commerce_order_save($order);
			drupal_goto('checkout/' . $order->order_id . '/complete' ) ;
		}
		return;
}
function commerce_gopcheckout_form_alter(&$form,&$form_state,$form_id) {
	global $user;
// Load cart order

	$order = commerce_cart_order_load($user->uid);
	if ($order)  {
  // Let's use the wrapper because it rocks
  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
  foreach ($order_wrapper->commerce_line_items as $delta => 
  	$line_item_wrapper) {
  	$line_item = $line_item_wrapper->value();
    }
}
	
	$addcartform = substr($form_id,0,30);
		switch ($addcartform) {
			case 'commerce_cart_add_to_cart_form':
			
			array_unshift($form['#submit'],
					'commerce_gopcheckout_processaddtocart');
			$form['line_item_fields']['field_wcgopmembername']['und']['0']['value']
				['#title'] = "If you are a member of the Washtenaw County Republican
				Party,<br>please enter your name in the box with the red border.  Then,
				<br>after you make your selection from the options list, click on the
				<br>Add To Cart button below";
			$form['line_item_fields']['field_wcgopmembername']['und']['#title'] = 
				"hidden";
			$form['line_item_fields']['field_wcgopmembername']['und']['0']
				['#weight'] = -10;
			$form['line_item_fields']['field_wcgopmembername']['#weight'] = '-15';
				foreach ($form['product_id']['#options'] as $key => $value) {
      		$form['product_id']['#options'][$key] = check_plain($value);
    		}
    		$form['line_item_fields']['#weight']= -5;	
		/*
			$form['product_id']['#type'] = 'radios';
			$form['line_item_fields']['field_mgdonationlevel']['und']['#title']=
				"<h3><strong>Please choose below the amount you wish to donate and then 
				click on the Add to Cart button</strong></h3>";
			$form['line_item_fields']['field_forumdonation']['und']['#title'] = "";
			$form['line_item_fields']['field_wcgopmember']['und']['#title'] = 
				"<strong>Please check this box if you are a member of the Washtenaw 
				County Republican Party</strong>";
			$form['line_item_fields']['field_wcgopmemberpurchase']['und']['#title'] = 
				"<strong>Please check this box if you would like to purchase a 
				membership in the Washtenaw County Republican Party</strong>";
			$form['line_item_fields']['field_wcgopattendevent']['und']['#title'] = 
				"<strong>Please check this box if you would like to attend the event, 
				but do not wish to purchase a WCGOP memberhship</strong>";
			$form['attributes']['field_forummenu']['#title']="";
			$form['attributes']['field_menu2017']['#title']="";
			$form['attributes']['field_sponsorship2017']['#title']="";
			$membersarray = array( 
		  	'visible' => array (
		     	':input[name="line_item_fields[field_wcgopmember][und]"]' => array(
		     		'checked' => TRUE)
		     	)
		  ); 
*/
//			$form['line_item_fields']['field_wcgopmembername']['#states'] = 
//				$membersarray;
			break;
	}
		switch ($form_id) {
			case 'views_form_commerce_cart_form_default':
					$order = commerce_cart_order_load($user->uid);
					$wrapper = entity_metadata_wrapper('commerce_order',$order);
					$order_total = $wrapper->commerce_order_total->value();
					$amount = commerce_currency_amount_to_decimal($order_total['amount'],'USD');
						if ($amount < 25) {
							$form['actions']['payatdoor']['#type'] = 'submit';
							$form['actions']['payatdoor']['#value'] = 'Pay at Door';
							$form['actions']['payatdoor']['#submit'] = array(
					  		'commerce_gopcheckout_setpayatdoor');
							$form['actions']['payatdoor']['#weight'] = '-1500';
					}
					if (in_array('superadmin user', array_values($user->roles))){
						$form['actions']['npc']['#type'] = 'submit';
						$form['actions']['npc']['#value'] = 'Non Paying Customer';
						$form['actions']['npc']['#submit'] = array(
							'commerce_gopcheckout_setpaidbyother');
						$form['actions']['npc']['#weight'] = '-1800';
					}
					
					break;
			case 'commerce_checkout_form_complete':
				$form['checkout_completion_message']['message']['#markup'] = 
					'<p><h3>Thank you for this order and for your continued support of 
					the Washtenaw County Republican Party!</h3></p>';
				break;
		}
	return;
}
function commerce_gopcheckout_setpayatdoor($form, &$form_state) {
	global $user;
	variable_set("aaa11","Made it into the commerce_gopcheckout_submit routine");
	$order = commerce_cart_order_load($user->uid);
	$order_wrapper = entity_metadata_wrapper('commerce_order', $order);
	$order_wrapper->field_payatdoor->set('1');	
	commerce_order_save($order);
	drupal_set_message('You made it into the button submit routine!');
	drupal_goto('checkout/' . $order->order_id);
}
function commerce_gopcheckout_setpaidbyother($form, &$form_state){
	global $user;
	$order = commerce_cart_order_load($user->uid);
	$order_wrapper = entity_metadata_wrapper('commerce_order', $order);
	$order_wrapper->field_paidbyotheriii->set('1');	
	commerce_order_save($order);
	drupal_goto('checkout/' . $order->order_id);
}
function commerce_gopcheckout_completenonpayingcustomer($form,$form_state){
	global $user;
	$order = commerce_cart_order_load($user->uid);
	commerce_order_status_update($order,'pending');
	$order_wrapper = entity_metadata_wrapper('commerce_order', $order);
	$targetorder = $form['customer_profile_guest']['field_orderattached']
		['und']['#value'];
	$order_wrapper->field_orderattached->set($targetorder);
	$order_wrapper->save();
}
function commerce_gopcheckout_finishmemberorder($form, &$form_state) {
	global $user;
	$order = commerce_cart_order_load($user->uid);
	$order_wrapper = entity_metadata_wrapper('commerce_order', $order);
	$order_total = $order_wrapper->commerce_order_total->value();
	$amount = commerce_currency_amount_to_decimal($order_total['amount'],'USD');
	if ( ($amount == 0 )|| $order_wrapper->field_payatdoor->raw() ){
		commerce_order_status_update($order,'pending');
		commerce_order_save($order);
		commerce_checkout_complete($order);
		drupal_goto('checkout/' . $order->order_id . '/complete' ) ;		
	}
	else {
		$customer_member = $order_wrapper->commerce_customer_member->value();
		if (isset($customer_member)){
			$customer_member_wrapper = $order_wrapper->commerce_customer_member;
			$customer_member_wrapper->field_wcgopmembername->
				set($order_wrapper->field_wcgopmembername->raw());
			$customer_member_wrapper->field_e_mail_address->set($form
				['customer_profile_member']['field_e_mail_address']['und']['0']['value']
				['#value']);
			$customer_member_wrapper->save();
		}
		else {
			watchdog('finishmemberorder','No member profile was available');
		}
		return;
	}
}
function commerce_gopcheckout_processaddtocart($form, &$form_state){
	global $user;
	$order = commerce_cart_order_load($user->uid);
	if (!$order) {
		$order = commerce_cart_order_new($user->uid);
	}
		$order_wrapper = entity_metadata_wrapper('commerce_order', $order);
		$wcgopname = $form['line_item_fields']['field_wcgopmembername']['und']
			['0']['value']['#value'];
		$order_wrapper->field_wcgopmembername->set($wcgopname);
		if (!empty($wcgopname) ){
			
			$order_wrapper->field_wcgopmember->set('1');
		}
		else {
			$order_wrapper->field_wcgopmember->set('0');
		}
		$order_wrapper->save();
	return;
}
function commerce_gopcheckout_commerce_email_order_items($variables) {

  // Get order wrapper.
  $order_wrapper = $variables['commerce_order_wrapper'];

  // Get rendered view.
  return views_embed_view('commerce_cart_summary', 'default', 
  	$order_wrapper->getIdentifier());
}

?>
